/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 35
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_system_marker = 1,
  sym_user_marker = 2,
  sym_assistant_marker = 3,
  sym_tool_use_marker = 4,
  sym_tool_result_marker = 5,
  aux_sym_inline_token1 = 6,
  sym_esc_prefix = 7,
  sym_text_line = 8,
  sym_document = 9,
  sym_preamble = 10,
  sym__block = 11,
  sym_system_block = 12,
  sym_user_block = 13,
  sym_assistant_block = 14,
  sym_tool_use_block = 15,
  sym_tool_result_block = 16,
  sym_inline = 17,
  sym_attrs = 18,
  sym_content = 19,
  sym__line = 20,
  sym_escaped_line = 21,
  sym_line_text = 22,
  aux_sym_document_repeat1 = 23,
  aux_sym_preamble_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_system_marker] = "system_marker",
  [sym_user_marker] = "user_marker",
  [sym_assistant_marker] = "assistant_marker",
  [sym_tool_use_marker] = "tool_use_marker",
  [sym_tool_result_marker] = "tool_result_marker",
  [aux_sym_inline_token1] = "inline_token1",
  [sym_esc_prefix] = "esc_prefix",
  [sym_text_line] = "text_line",
  [sym_document] = "document",
  [sym_preamble] = "preamble",
  [sym__block] = "_block",
  [sym_system_block] = "system_block",
  [sym_user_block] = "user_block",
  [sym_assistant_block] = "assistant_block",
  [sym_tool_use_block] = "tool_use_block",
  [sym_tool_result_block] = "tool_result_block",
  [sym_inline] = "inline",
  [sym_attrs] = "attrs",
  [sym_content] = "content",
  [sym__line] = "_line",
  [sym_escaped_line] = "escaped_line",
  [sym_line_text] = "line_text",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_preamble_repeat1] = "preamble_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_system_marker] = sym_system_marker,
  [sym_user_marker] = sym_user_marker,
  [sym_assistant_marker] = sym_assistant_marker,
  [sym_tool_use_marker] = sym_tool_use_marker,
  [sym_tool_result_marker] = sym_tool_result_marker,
  [aux_sym_inline_token1] = aux_sym_inline_token1,
  [sym_esc_prefix] = sym_esc_prefix,
  [sym_text_line] = sym_text_line,
  [sym_document] = sym_document,
  [sym_preamble] = sym_preamble,
  [sym__block] = sym__block,
  [sym_system_block] = sym_system_block,
  [sym_user_block] = sym_user_block,
  [sym_assistant_block] = sym_assistant_block,
  [sym_tool_use_block] = sym_tool_use_block,
  [sym_tool_result_block] = sym_tool_result_block,
  [sym_inline] = sym_inline,
  [sym_attrs] = sym_attrs,
  [sym_content] = sym_content,
  [sym__line] = sym__line,
  [sym_escaped_line] = sym_escaped_line,
  [sym_line_text] = sym_line_text,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_preamble_repeat1] = aux_sym_preamble_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_system_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_user_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_assistant_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_use_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_result_marker] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_inline_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_esc_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_preamble] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_system_block] = {
    .visible = true,
    .named = true,
  },
  [sym_user_block] = {
    .visible = true,
    .named = true,
  },
  [sym_assistant_block] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_use_block] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_result_block] = {
    .visible = true,
    .named = true,
  },
  [sym_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_attrs] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_escaped_line] = {
    .visible = true,
    .named = true,
  },
  [sym_line_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_preamble_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '%') ADVANCE(9);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 1:
      if (eof) ADVANCE(2);
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '%') ADVANCE(55);
      if (lookahead != 0) ADVANCE(113);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_system_marker);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_user_marker);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_assistant_marker);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_tool_use_marker);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_tool_result_marker);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == '%') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == '%') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == '%') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == ':') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == '[') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == '[') ADVANCE(22);
      if (lookahead == 's') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == ']') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == ']') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == ']') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == '_') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'a') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'a') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'a') ADVANCE(46);
      if (lookahead == 's') ADVANCE(52);
      if (lookahead == 't') ADVANCE(33);
      if (lookahead == 'u') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'c') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'e') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'e') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'e') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'e') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'e') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'i') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'l') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'l') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'm') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'n') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'o') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'o') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'p') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'r') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'r') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'r') ADVANCE(26);
      if (lookahead == 'u') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 's') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 's') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 's') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 's') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 's') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 's') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 's') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 's') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 's') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 't') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 't') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 't') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 't') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'u') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead == 'y') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_inline_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_esc_prefix);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '%') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '%') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '%') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '%') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '%') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '%') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '%') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '%') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '%') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '%') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '%') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == ':') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '[') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '[') ADVANCE(81);
      if (lookahead == 's') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == ']') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == ']') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == ']') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == ']') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == ']') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == ']') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == ']') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '_') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'a') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'a') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'a') ADVANCE(105);
      if (lookahead == 's') ADVANCE(112);
      if (lookahead == 't') ADVANCE(92);
      if (lookahead == 'u') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'c') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'e') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'e') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'e') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'e') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'e') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'i') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'l') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'l') ADVANCE(110);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'm') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'n') ADVANCE(109);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'o') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'o') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'p') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'r') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'r') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'r') ADVANCE(84);
      if (lookahead == 'u') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 's') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 's') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 's') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 's') ADVANCE(111);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 's') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 's') ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 's') ADVANCE(107);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 's') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 's') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 't') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 't') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 't') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 't') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 't') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'u') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'y') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_system_marker] = ACTIONS(1),
    [sym_user_marker] = ACTIONS(1),
    [sym_assistant_marker] = ACTIONS(1),
    [sym_tool_use_marker] = ACTIONS(1),
    [sym_tool_result_marker] = ACTIONS(1),
    [aux_sym_inline_token1] = ACTIONS(1),
    [sym_esc_prefix] = ACTIONS(1),
    [sym_text_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(34),
    [sym_preamble] = STATE(8),
    [sym__block] = STATE(9),
    [sym_system_block] = STATE(9),
    [sym_user_block] = STATE(9),
    [sym_assistant_block] = STATE(9),
    [sym_tool_use_block] = STATE(9),
    [sym_tool_result_block] = STATE(9),
    [sym__line] = STATE(16),
    [sym_escaped_line] = STATE(16),
    [aux_sym_document_repeat1] = STATE(9),
    [aux_sym_preamble_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_system_marker] = ACTIONS(5),
    [sym_user_marker] = ACTIONS(7),
    [sym_assistant_marker] = ACTIONS(9),
    [sym_tool_use_marker] = ACTIONS(11),
    [sym_tool_result_marker] = ACTIONS(13),
    [sym_esc_prefix] = ACTIONS(15),
    [sym_text_line] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym_inline] = STATE(11),
    [sym_content] = STATE(25),
    [sym__line] = STATE(17),
    [sym_escaped_line] = STATE(17),
    [aux_sym_preamble_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_system_marker] = ACTIONS(21),
    [sym_user_marker] = ACTIONS(21),
    [sym_assistant_marker] = ACTIONS(21),
    [sym_tool_use_marker] = ACTIONS(21),
    [sym_tool_result_marker] = ACTIONS(21),
    [aux_sym_inline_token1] = ACTIONS(23),
    [sym_esc_prefix] = ACTIONS(25),
    [sym_text_line] = ACTIONS(27),
  },
  [STATE(3)] = {
    [sym_inline] = STATE(12),
    [sym_content] = STATE(24),
    [sym__line] = STATE(17),
    [sym_escaped_line] = STATE(17),
    [aux_sym_preamble_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_system_marker] = ACTIONS(31),
    [sym_user_marker] = ACTIONS(31),
    [sym_assistant_marker] = ACTIONS(31),
    [sym_tool_use_marker] = ACTIONS(31),
    [sym_tool_result_marker] = ACTIONS(31),
    [aux_sym_inline_token1] = ACTIONS(23),
    [sym_esc_prefix] = ACTIONS(25),
    [sym_text_line] = ACTIONS(27),
  },
  [STATE(4)] = {
    [sym_inline] = STATE(13),
    [sym_content] = STATE(26),
    [sym__line] = STATE(17),
    [sym_escaped_line] = STATE(17),
    [aux_sym_preamble_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_system_marker] = ACTIONS(35),
    [sym_user_marker] = ACTIONS(35),
    [sym_assistant_marker] = ACTIONS(35),
    [sym_tool_use_marker] = ACTIONS(35),
    [sym_tool_result_marker] = ACTIONS(35),
    [aux_sym_inline_token1] = ACTIONS(23),
    [sym_esc_prefix] = ACTIONS(25),
    [sym_text_line] = ACTIONS(27),
  },
  [STATE(5)] = {
    [sym_attrs] = STATE(14),
    [sym_content] = STATE(27),
    [sym__line] = STATE(17),
    [sym_escaped_line] = STATE(17),
    [aux_sym_preamble_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_system_marker] = ACTIONS(39),
    [sym_user_marker] = ACTIONS(39),
    [sym_assistant_marker] = ACTIONS(39),
    [sym_tool_use_marker] = ACTIONS(39),
    [sym_tool_result_marker] = ACTIONS(39),
    [aux_sym_inline_token1] = ACTIONS(41),
    [sym_esc_prefix] = ACTIONS(25),
    [sym_text_line] = ACTIONS(27),
  },
  [STATE(6)] = {
    [sym_attrs] = STATE(15),
    [sym_content] = STATE(28),
    [sym__line] = STATE(17),
    [sym_escaped_line] = STATE(17),
    [aux_sym_preamble_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(43),
    [sym_system_marker] = ACTIONS(45),
    [sym_user_marker] = ACTIONS(45),
    [sym_assistant_marker] = ACTIONS(45),
    [sym_tool_use_marker] = ACTIONS(45),
    [sym_tool_result_marker] = ACTIONS(45),
    [aux_sym_inline_token1] = ACTIONS(41),
    [sym_esc_prefix] = ACTIONS(25),
    [sym_text_line] = ACTIONS(27),
  },
  [STATE(7)] = {
    [sym__block] = STATE(7),
    [sym_system_block] = STATE(7),
    [sym_user_block] = STATE(7),
    [sym_assistant_block] = STATE(7),
    [sym_tool_use_block] = STATE(7),
    [sym_tool_result_block] = STATE(7),
    [aux_sym_document_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym_system_marker] = ACTIONS(49),
    [sym_user_marker] = ACTIONS(52),
    [sym_assistant_marker] = ACTIONS(55),
    [sym_tool_use_marker] = ACTIONS(58),
    [sym_tool_result_marker] = ACTIONS(61),
  },
  [STATE(8)] = {
    [sym__block] = STATE(10),
    [sym_system_block] = STATE(10),
    [sym_user_block] = STATE(10),
    [sym_assistant_block] = STATE(10),
    [sym_tool_use_block] = STATE(10),
    [sym_tool_result_block] = STATE(10),
    [aux_sym_document_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(64),
    [sym_system_marker] = ACTIONS(5),
    [sym_user_marker] = ACTIONS(7),
    [sym_assistant_marker] = ACTIONS(9),
    [sym_tool_use_marker] = ACTIONS(11),
    [sym_tool_result_marker] = ACTIONS(13),
  },
  [STATE(9)] = {
    [sym__block] = STATE(7),
    [sym_system_block] = STATE(7),
    [sym_user_block] = STATE(7),
    [sym_assistant_block] = STATE(7),
    [sym_tool_use_block] = STATE(7),
    [sym_tool_result_block] = STATE(7),
    [aux_sym_document_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(64),
    [sym_system_marker] = ACTIONS(5),
    [sym_user_marker] = ACTIONS(7),
    [sym_assistant_marker] = ACTIONS(9),
    [sym_tool_use_marker] = ACTIONS(11),
    [sym_tool_result_marker] = ACTIONS(13),
  },
  [STATE(10)] = {
    [sym__block] = STATE(7),
    [sym_system_block] = STATE(7),
    [sym_user_block] = STATE(7),
    [sym_assistant_block] = STATE(7),
    [sym_tool_use_block] = STATE(7),
    [sym_tool_result_block] = STATE(7),
    [aux_sym_document_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(66),
    [sym_system_marker] = ACTIONS(5),
    [sym_user_marker] = ACTIONS(7),
    [sym_assistant_marker] = ACTIONS(9),
    [sym_tool_use_marker] = ACTIONS(11),
    [sym_tool_result_marker] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(15), 1,
      sym_esc_prefix,
    ACTIONS(27), 1,
      sym_text_line,
    STATE(29), 1,
      sym_content,
    STATE(17), 3,
      sym__line,
      sym_escaped_line,
      aux_sym_preamble_repeat1,
    ACTIONS(68), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [23] = 5,
    ACTIONS(15), 1,
      sym_esc_prefix,
    ACTIONS(27), 1,
      sym_text_line,
    STATE(30), 1,
      sym_content,
    STATE(17), 3,
      sym__line,
      sym_escaped_line,
      aux_sym_preamble_repeat1,
    ACTIONS(70), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [46] = 5,
    ACTIONS(15), 1,
      sym_esc_prefix,
    ACTIONS(27), 1,
      sym_text_line,
    STATE(31), 1,
      sym_content,
    STATE(17), 3,
      sym__line,
      sym_escaped_line,
      aux_sym_preamble_repeat1,
    ACTIONS(72), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [69] = 5,
    ACTIONS(15), 1,
      sym_esc_prefix,
    ACTIONS(27), 1,
      sym_text_line,
    STATE(32), 1,
      sym_content,
    STATE(17), 3,
      sym__line,
      sym_escaped_line,
      aux_sym_preamble_repeat1,
    ACTIONS(74), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [92] = 5,
    ACTIONS(15), 1,
      sym_esc_prefix,
    ACTIONS(27), 1,
      sym_text_line,
    STATE(33), 1,
      sym_content,
    STATE(17), 3,
      sym__line,
      sym_escaped_line,
      aux_sym_preamble_repeat1,
    ACTIONS(76), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [115] = 4,
    ACTIONS(15), 1,
      sym_esc_prefix,
    ACTIONS(80), 1,
      sym_text_line,
    STATE(18), 3,
      sym__line,
      sym_escaped_line,
      aux_sym_preamble_repeat1,
    ACTIONS(78), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [135] = 4,
    ACTIONS(15), 1,
      sym_esc_prefix,
    ACTIONS(80), 1,
      sym_text_line,
    STATE(18), 3,
      sym__line,
      sym_escaped_line,
      aux_sym_preamble_repeat1,
    ACTIONS(82), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [155] = 4,
    ACTIONS(86), 1,
      sym_esc_prefix,
    ACTIONS(89), 1,
      sym_text_line,
    STATE(18), 3,
      sym__line,
      sym_escaped_line,
      aux_sym_preamble_repeat1,
    ACTIONS(84), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [175] = 4,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 1,
      aux_sym_inline_token1,
    STATE(22), 1,
      sym_line_text,
    ACTIONS(94), 7,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
      sym_esc_prefix,
      sym_text_line,
  [194] = 2,
    ACTIONS(100), 1,
      sym_text_line,
    ACTIONS(98), 7,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
      sym_esc_prefix,
  [207] = 2,
    ACTIONS(104), 1,
      sym_text_line,
    ACTIONS(102), 7,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
      sym_esc_prefix,
  [220] = 2,
    ACTIONS(108), 1,
      sym_text_line,
    ACTIONS(106), 7,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
      sym_esc_prefix,
  [233] = 2,
    ACTIONS(112), 1,
      sym_text_line,
    ACTIONS(110), 7,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
      sym_esc_prefix,
  [246] = 1,
    ACTIONS(70), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [255] = 1,
    ACTIONS(68), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [264] = 1,
    ACTIONS(72), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [273] = 1,
    ACTIONS(74), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [282] = 1,
    ACTIONS(76), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [291] = 1,
    ACTIONS(114), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [300] = 1,
    ACTIONS(116), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [309] = 1,
    ACTIONS(118), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [318] = 1,
    ACTIONS(120), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [327] = 1,
    ACTIONS(122), 6,
      ts_builtin_sym_end,
      sym_system_marker,
      sym_user_marker,
      sym_assistant_marker,
      sym_tool_use_marker,
      sym_tool_result_marker,
  [336] = 1,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 23,
  [SMALL_STATE(13)] = 46,
  [SMALL_STATE(14)] = 69,
  [SMALL_STATE(15)] = 92,
  [SMALL_STATE(16)] = 115,
  [SMALL_STATE(17)] = 135,
  [SMALL_STATE(18)] = 155,
  [SMALL_STATE(19)] = 175,
  [SMALL_STATE(20)] = 194,
  [SMALL_STATE(21)] = 207,
  [SMALL_STATE(22)] = 220,
  [SMALL_STATE(23)] = 233,
  [SMALL_STATE(24)] = 246,
  [SMALL_STATE(25)] = 255,
  [SMALL_STATE(26)] = 264,
  [SMALL_STATE(27)] = 273,
  [SMALL_STATE(28)] = 282,
  [SMALL_STATE(29)] = 291,
  [SMALL_STATE(30)] = 300,
  [SMALL_STATE(31)] = 309,
  [SMALL_STATE(32)] = 318,
  [SMALL_STATE(33)] = 327,
  [SMALL_STATE(34)] = 336,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_block, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_system_block, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_block, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_user_block, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assistant_block, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assistant_block, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_use_block, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tool_use_block, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_result_block, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tool_result_block, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_block, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_block, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assistant_block, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_use_block, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_result_block, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preamble, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escaped_line, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escaped_line, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attrs, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attrs, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escaped_line, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escaped_line, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_text, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_text, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_block, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_block, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assistant_block, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_use_block, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_result_block, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_straps(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
